Lesson 11
kaltag/Think_Rails pull request #12
Opened 2023-05-01 16:06 UTC by kaltag

1. Реализуйте аутентификацию в проекте при помощи библиотеки Devise
2. Сделайте управление ресурсами вопросов и ответов доступным только для администраторов
3. С помощью хэлпера Devise реализуйте перенаправление администраторов на страницу /admin/tests после логина
4. При создании нового теста администратором назначайте его в качестве автора теста

2023-05-01 18:11 UTC, BubuntuClu requested changes

2023-05-01 18:11 UTC, BubuntuClu commented on app/controllers/admin/answers_controller.rb
> +  before_action :authenticate_user!
это дубль вызова. этот колбэк определен в родительском контроллере

2023-05-01 18:11 UTC, BubuntuClu commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'You are not admin. Go away!' unless current_user.type == 'Admin'
сделай метод в моделе пользователя `admin?` и вызывай его тут

2023-05-01 18:11 UTC, BubuntuClu commented on app/controllers/admin/questions_controller.rb
> +  before_action :authenticate_user!
дубль колбэка

2023-05-01 18:11 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +  before_action :authenticate_user!
дубль колбэка

2023-05-01 18:11 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    if current_user.type == 'Admin'
`current_user.admin?`

2023-05-01 18:11 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :authenticate_user!
а стоило выносить `before_action :authenticate_user!` в админ контроллер, если в основном приложении это тоже нужно? кажется этот колбэк надо оставить в `ApplicationController` и все

2023-05-01 18:11 UTC, BubuntuClu commented on app/models/admin.rb
> +  validates :first_name, presence: true
>При регистрации пользователя запрашивать его имя и фамилию и после входа, выводить флэш-сообщение "Привет, <имя пользователя>!" 

не нашел использования этих полей. ты сделал это задание?

2023-05-02 08:24 UTC, kaltag commented on app/models/admin.rb
> +  validates :first_name, presence: true
https://github.com/kaltag/Testing-applications/pull/12/commits/c5fdb14f18ceca4e4a142d6174c36a091a5f1e1d

2023-05-02 13:47 UTC, merged