add i18n
kaltag/Think_Rails pull request #13
Opened 2023-05-03 16:21 UTC by kaltag

1.Полностью локализуйте ресурсы:
Тестов для пользователя
Тестов для администратора
Прохождения тестов для пользователя (пункт выполняется по желанию)

2. Локализуйте представления Devise (вы можете использовать готовые тексты: [github.com](https://github.com/plataformatec/devise/wiki/I18n))

3. Сделайте так чтобы по умолчанию URL параметр языка не добавлялся в том случае когда установленная локаль такая же как локаль по умолчанию

4. При создании нового теста определите перевод для подсказки в списке категорий (используйте исходный код Rails для поиска подходящей последовательности ключей: [github.com](https://github.com/rails/rails/blob/master/actionview/lib/action_view/locale/en.yml))

2023-05-03 17:05 UTC, BubuntuClu requested changes

2023-05-03 17:05 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    { locale: I18n.locale }
>3. Сделайте так чтобы по умолчанию URL параметр языка не добавлялся в том случае когда установленная локаль такая же как локаль по умолчанию

кажется, тут это не учитывается

2023-05-03 17:05 UTC, BubuntuClu commented on config/routes.rb
> +  scope '(:locale)', locale: /ru|en/ do
что делает параметр `locale: /ru|en/`?

может ты констрейнт хотел задать? `constraints: { locale: /ru|en/ }`

2023-05-04 07:44 UTC, kaltag commented on config/routes.rb
> +  scope '(:locale)', locale: /ru|en/ do
http://rusrails.ru/i18n#naznachenie-lokali-iz-parametrov-url
![image](https://user-images.githubusercontent.com/44153751/236141213-01643f67-e3d2-41be-8f28-6dcf01b95bcb.png)
использовал так чтобы url выглядело так -
http://127.0.0.1:3000/ru/gurus/login
http://127.0.0.1:3000/ru/test_passages/10

2023-05-04 07:50 UTC, kaltag commented on app/controllers/application_controller.rb
> +    { locale: I18n.locale }
https://github.com/kaltag/Testing-applications/pull/13/commits/3e50f1869f90ab6b3589317397a0a22867cfd210

2023-05-04 10:23 UTC, merged