Lesson 4
kaltag/Think_Rails pull request #3
Opened 2023-04-13 13:15 UTC by kaltag

- Создайте набор начальных данных для всех существующих моделей в файле db/seeds.rb

- Создайте инстанс-метод в модели User, который принимает в качестве аргумента значение уровня сложности и возвращает список всех Тестов, которые проходит или когда-либо проходил Пользователь на этом уровне сложности

- Создайте метод класса в модели Test, который возвращает отсортированный по убыванию массив названий всех Тестов у которых Категория называется определённым образом (название категории передается в метод в качестве аргумента).

2023-04-13 16:29 UTC, BubuntuClu requested changes

2023-04-13 16:29 UTC, BubuntuClu commented on app/models/user.rb
> +  def method_name(user, level)
это инстанс метод. метод вызывается на объекте пользователя. значит тебе не надо сюда пользователя передавать

2023-04-13 16:29 UTC, BubuntuClu commented on app/models/user.rb
> +  # я не смог придумать как без ассоциаций и общей таблицы сохранять тесты которые проходил юзер. Так же я добавил в параметры самого юзера,
по0другому и не сделать. тут нужна соединительная таблица

2023-04-13 16:29 UTC, BubuntuClu commented on db/migrate/20230413125356_create_tests_users_join_table.rb
> +      t.index :test_id
внешние ключи забыл добавить
и я бы рекомендовал не делать таблицу без ID, ты никогда не знаешь какие будут требования к системе. сегодня одно, а завтра другое и тебе надо работать с конкретной строкой соединительной таблицы, а у тебя нет в ней первичного ключа. добавлять его будет немного геморно потом

2023-04-13 19:14 UTC, kaltag commented on db/migrate/20230413125356_create_tests_users_join_table.rb
> +      t.index :test_id
тут я использовал гайд http://rusrails.ru/active-record-associations#sozdanie-soedinitelnyh-tablits-dlya-svyazey-has_and_belongs_to_many
 
![image](https://user-images.githubusercontent.com/44153751/231860162-a7c38ab1-f76e-40ab-b4f6-5f72992dd7e1.png)

По итогу на практике как лучше, по гайду или все таки c ID

А еще по логике тут внешние ключи сами добавились, тк create_join_table (судя по гайду)

2023-04-14 07:11 UTC, BubuntuClu commented on db/migrate/20230413125356_create_tests_users_join_table.rb
> +      t.index :test_id
создались внешние ключи или нет, ты можешь посмотреть в schema.rb. в самом низу файла пишутся внешние ключи;. сейчас там нет ключей для этой таблицы

2023-04-14 07:11 UTC, BubuntuClu commented on db/migrate/20230413125356_create_tests_users_join_table.rb
> +      t.index :test_id
я топлю за ID. ты можешь оставить сейчас так и потом посмотреть к чему это может привести. и сравнить подходы на практике

2023-04-14 11:21 UTC, merged