Lesson 8
kaltag/Think_Rails pull request #9
Opened 2023-04-23 15:42 UTC by kaltag

1. Реализуйте все стандартные действия вместе с представлениями (видами) для ресурса вопросов:

- Список вопросов теста должен выводиться на той же странице, что и сам тест
- Используйте фрагменты представлений там, где это уместно
- Для того чтобы метод form_with смог сформировать верный URL используйте вызов form_with model: [@parent, @child]
- В представлениях должны быть ссылки для навигации между страницами приложения

2. Добавьте футер в котором будет выводиться текущий год, имя автора, название проекта (в виде ссылки на GitHub-репозиторий проекта), его краткое описание и ссылка с текстом "Учебный проект в онлайн-школе Thinknetica", ведущая на адрес [thinknetica.com](http://thinknetica.com/)
3. Напишите хэлперы:

- Для заголовка формы создания и редактирования вопроса. Это должен быть один метод question_header который в форме создания вопроса будет выводить Create New <Test Title> Question, а в форме редактирования Edit <Test Title> Question
- Для вывода текущего года в футере
- Для формирования ссылки на GitHub репозиторий: github_url(author, repo)

4. Добавьте в представление списка тестов количество вопросов для каждого теста

2023-04-23 17:23 UTC, BubuntuClu requested changes

2023-04-23 17:23 UTC, BubuntuClu commented on app/helpers/question_helper.rb
> +  def question_header(test)
может быть так, что заголовок тебе надо показвать не только на этих экшенах. в этом случае код не будет работать и надо будет вносить доработки.

если ты будешь полагаться на состояние объекта persisted?/new_record? то код будет более универсальным и не будет требовать доп манипуляций с ним

передавай явно объект вопроса и работай с ним в этом методе. тест можно получить по ассоциации от вопроса

2023-04-23 17:23 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<h1><%= question_header(@question.test) %></h1>
какой смысл размещать этот метод в отдельной вьюхе, а не в общей? ты тут уже можешь и заголовок нужный сразу указать.

по идеи вьюхи edit/new должно состоять только из строки `<%= render 'form', question: @question %>`, так как весь их код одинаковый и все описывается во вьюхе формы

2023-04-23 17:23 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<h1><%= question_header(@question.test) %></h1>
можно еще укоротить оставив только рендер форм. а инстанс переменную вопроса использовать во вьюхе формы. но так могут возникнуть вопросы, а откуда берется объект. лучше явно все передавать, и тест туда же прокинуть

2023-04-23 17:23 UTC, BubuntuClu commented on db/seeds.rb
> +15.times { Category.create(title: Faker::ProgrammingLanguage.name) }
хоть это и сид, который выполняется редко, но нем отрабатываем навыки. ты тут много лишних запросов в БД генерируешь. был код лучше, ты испортил. ты создаешь категории, но не сохраняешь объекты, и потом о5 лезешь за только что созданными категориями.
тебе в сидах не нужно много данных генерировать, так что лучше вернуться к старой записи сида. либо тут переделывать алгоритм работы с созданными объектами

2023-04-24 07:06 UTC, BubuntuClu commented on app/helpers/question_helper.rb
> +  def question_header(object, test)
просто `object` и от него `object.test`. так ты уменьшишь количество аргументов для метода. чем меньше аргументов, тем лучше

2023-04-24 07:09 UTC, kaltag commented on app/helpers/question_helper.rb
> +  def question_header(object, test)
Тут проблема в том, что при создание нового вопроса, его не существует и я не могу от него тест вытащить, поэтому я так сделал

2023-04-24 13:19 UTC, merged